### ISSUE TITLE
Network image creation seems to have duplicate nodes

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#113]
## Problem Definition

When I look at the graps generated from the networks they seem to have a lot of common nodes, it seems like the canvas is not cleared before drawing the next graph.

![graph-0x0e97bebee751d9312610ac4c3974d355cc330e68](https://user-images.githubusercontent.com/90851/50163074-f69da580-02df-11e9-9b58-f259b64db9f0.png)
![graph-0x5ad68f3d34d3dd2a9a39d9d27f2158db7cd00674](https://user-images.githubusercontent.com/90851/50163075-f69da580-02df-11e9-8d2f-4a9e83b48e1d.png)

**Comment by Dominik1999** [comment]
thanks for letting me know

**Comment by Dominik1999** [comment]
Closed by #115
