### ISSUE TITLE
Spec Open Questions

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-pathfinding-service#2]
These were removed from the spec.

* How do clients open channels? Additional service offered by the pathfinding server?
* Is it OK to assume that clients address in the RDN token network is the same as in the (possibly) different network it asks the pathfinding service for a path?
* Are the updating endpoints publicly available or just for the matrix channel listener?

@palango Please address them one by one and incorporate the correct answers into the spec and eventually into the code.

**Comment by palango** [comment]
Added #4, #5 and #6.
