### ISSUE TITLE
Fee representation convention

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden-pathfinding-service#55]
Decide on how to represent fees, i.e. use percent (with float), use basis points, come up with an own convention.

**Comment by LefterisJP** [comment]
Basis points, as long as the granularity is fine enough (i.e. 1 millionth) should be good enough imo.

**Comment by LefterisJP** [comment]
> which we define to be 1/1_000_000 of a percent

Hmm .. that sounds weird. A basis point is [defined](https://en.wikipedia.org/wiki/Basis_point) as 1/10,000.

We can redefine it for our purpose or call it something else. Just 1 millionth. So 1 out of a million, not 1 out of a milltion of a percent. Or maybe I misunderstood?

**Comment by palango** [comment]
So we make it 1/1,000,000 instead?

**Comment by err508** [comment]
That sounds better, I think `1/1_000_000 of a percent` would be a little over the top.

**Comment by LefterisJP** [comment]
Yep. It even has a name:

> One part per million (ppm) denotes one part per 1000000 parts, one part in 106, 1/1000000 × 100% = 0.0001% (or 1% = 10000 ppm), and a value of 1 × 10−6. This is equivalent to about 32 seconds out of a year; in distance measurement, it is equivalent to 1 mm of error per km of distance traversed.

[source](https://en.wikipedia.org/wiki/Parts-per_notation)

**Comment by err508** [comment]
It's in a way a pretty ambitious statement towards finance, as we state implicitly that we expect to need 100 times more precision (or 100 times lower fees) than classical finance.

**Comment by palango** [comment]
Fixed by #60
