### ISSUE TITLE
[Spec] Public REST endpoints or pure matrix communication

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#6]
Once we know more about the Matrix transport we have to decide whether we will provide a public REST API or just accept communication over Matrix.

**Comment by devium** [comment]
The initial reasoning behind the REST API was that it provides a public transport-layer-agnostic and sustainable interface in case the transport layer changes.

I mean we could still say that the `TokenNetwork.update_balance()` provides that interface but that would not be a public (or network-facing) one.

Debatable whether we need a network-facing, transport-layer-agnostic interface at all but right now I'd say it doesn't hurt and provides some nice flexibility.

**Comment by pcppcp** [comment]
I agree with @devium, it's very useful to have a REST endpoint for common functions, it makes testing much easier. It can be optionally enabled in the production.

**Comment by palango** [comment]
Agreement is that we want a REST API at least for testing. Opened #35 to track that.
