### ISSUE TITLE
Pathfinding algorithms

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#7]
Research and implement suitable pathfinding algorithms on different network topologies and scenarios.

Requirements are:
- only return routes that have capacity >= transfer amount
- minimize/maximize some route property (might be fees, hops, some combination, ...)
- return multiple routes, especially (partially) non-overlapping

**Comment by devium** [comment]
Discussed this with @err508: We will probably ignore fees for now until the fee model is specced out.

Until then we will just work on capacity-based routing. @err508 is working on that, including some fixtures helpful for benchmarking different algorithms.

**Comment by devium** [comment]
Update: fees are supported in the current implementation but unless they are explicitly updated (via a signed message), we just assume a default fee of `DEFAULT_FEE` in the channels. In the case of no fees being reported (i.e. all fees being equal to `DEFAULT_FEE`), paths are simply prioritized by their number of hops.

**Comment by palango** [comment]
The three requirements are solved by the current implementation. If there are specific problems we can open issues for them.
