### ISSUE TITLE
[tmp] PFS Planning

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#77]
Copied from https://github.com/raiden-network/raiden/issues/2704

# PFS planning

To plan the integration of the PFS I want to get a discussion started here. Below is a four step plan that marks useful milestones for the PFS and its integration and provides time for parallel development of requirements for stages (e.g. matrix room for sharing balance proofs (which will be used for the MS as well), decision on fees in the client).

Before specing this out further I'd like to get some feedback.

#### PFS
- [ ] Index events, recreate topology from them
- [ ] Provide endpoint to get routes
#### Raiden
- [ ] Remove internal topology state
- [ ] Request route information during payment initialisation
- [ ] Fixtures for spawning the PFS during tests

#### PFS
- [ ] Include endpoint to provide balance updates
- [ ] Include balances in route calculations
#### Raiden
- [ ] Send balance updates to PFS

#### PFS
- [ ] Include endpoint to provide fee updates
- [ ] Include fees in route calculations
#### Raiden
- [ ] Requirement: have fees implemented
- [ ] Send fee updates to PFS

#### PFS
- [ ] Decide on payment method.

**Comment by LefterisJP** [comment]
Question: Integration tests for these should be done in Raiden repo I guess? Or in the mono-repo we discussed?


> Pay for PFS when over free-tier

So we will definitely have a free tier after all? How much will that be? Is there a discussion anywhere?

**Comment by palango** [comment]
General disclaimer, I just copied this issue from the raiden repo, it's not up to date.

> Question: Integration tests for these should be done in Raiden repo I guess?

I'd say so, not sure atm what the best way to do this is.

> So we will definitely have a free tier after all? How much will that be? Is there a discussion anywhere?

Before this is decided we need to decide on a payment method, we working on an overview for that right now.

**Comment by palango** [comment]
This is outdated as of the latest planning, I'll create a new roadmap asap.
