### ISSUE TITLE
Blockchain listener

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#8]
Integrate a blockchain listener to react on new events.

- [x] Initial integration
- [ ] Testing

**Comment by LefterisJP** [comment]
@palango Since I see the initial integration checkbox ticked I would like to also be able to see which commit/PR did it. Can you get in the habit of referring to issues from inside commit text?

**Comment by palango** [comment]
Yes, will do. There weren't any issues when the initial implementation was done. Now everything the more organized :)

**Comment by palango** [comment]
An integration fix is now in raiden-libs. Closing.
