### ISSUE TITLE
Matrix listener

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#9]
Add a matrix listener to get balance proofs and/or fee updates.

- [x] Add matrix listener, connect it to PathfindingService
- [x] Define `BalanceProof` message ~that includes all `Locks`~
  - BalanceProof now includes  `locked_amount`
- [x] Define `FeeUpdate` message
- [x] Define `PathsRequest` message #50 
- [x] Integrate message verification once the message format is specified
  - [x] `FeeInfo`
  - [x] `BalanceProof`
  - [x] `PathsRequest`
- [x] Remove `model/BalanceProof` and `model/Lock` classes.

**Comment by pcppcp** [comment]
I guess I can work on that, I'll move current transport code to libs and then extend it depending on requirements.

**Comment by palango** [comment]
Yes, we can work on the code in libs together. I will do the PFS integration.

**Comment by palango** [comment]
Blocked by raiden-network/raiden-libs#43
